const formJson = {
    json1 : [{
        'val': [],
        'fn': 'id',
        'fp': {},
        'cn': '序号',
        'id': 'a1',
        'ft': ''
    }, {
        'val': [],
        'fn': 'createTime',
        'fp': {},
        'cn': '数据生产时间',
        'id': 'a2',
        'ft': ''
    }, {
        'val': [],
        'fn': 'd1Dg',
        'fp': {},
        'cn': '导高(mm)',
        'id': 'a3',
        'ft': ''
    }, {
        'val': [],
        'fn': 'd1Lcz',
        'fp': {},
        'cn': '拉出值(mm)',
        'id': 'a4',
        'ft': ''
    }, {
        'val': [],
        'fn': 'd1Gj',
        'fp': {},
        'cn': '轨距(mm)',
        'id': 'a5',
        'ft': ''
    }, {
        'val': [],
        'fn': 'd1Cg',
        'fp': {},
        'cn': '超高(mm)',
        'id': 'a6',
        'ft': ''
    }],
    json2 : [{
        'val': [],
        'fn': 'id',
        'fp': {},
        'cn': '序号',
        'id': 'b1',
        'ft': ''
    }, {
        'val': [],
        'fn': 'createTime',
        'fp': {},
        'cn': '数据生产时间',
        'id': 'b2',
        'ft': ''
    }, {
        'val': [],
        'fn': 'd2Dg',
        'fp': {},
        'cn': '导高(mm)',
        'id': 'b3',
        'ft': ''
    }, {
        'val': [],
        'fn': 'd2Plz',
        'fp': {},
        'cn': '偏离值(mm)',
        'id': 'b4',
        'ft': ''
    }, {
        'val': [],
        'fn': 'd2Ngj',
        'fp': {},
        'cn': '内轨距(mm)',
        'id': 'b5',
        'ft': ''
    }],
    json3 : [{
        'val': [],
        'fn': 'id',
        'fp': {},
        'cn': '序号',
        'id': 1,
        'ft': ''
    }, {
        'val': [],
        'fn': 'createTime',
        'fp': {},
        'cn': '数据生产时间',
        'id': 2,
        'ft': ''
    }, {
        'val': [],
        'fn': 'd3Hxbg',
        'fp': {},
        'cn': '红线标高(mm)',
        'id': 3,
        'ft': ''
    }, {
        'val': [],
        'fn': 'd3Clxj',
        'fp': {},
        'cn': '测量限界(mm)',
        'id': 4,
        'ft': ''
    }],
    json4 : [{
        'val': [],
        'fn': 'id',
        'fp': {},
        'cn': '序号',
        'id': 1,
        'ft': ''
    }, {
        'val': [],
        'fn': 'createTime',
        'fp': {},
        'cn': '数据生产时间',
        'id': 2,
        'ft': ''
    }, {
        'val': [],
        'fn': 'd5Fztg',
        'fp': {},
        'cn': '非支抬高(mm)',
        'id': 3,
        'ft': ''
    }, {
        'val': [],
        'fn': 'd5Fzpl',
        'fp': {},
        'cn': '非支偏离(mm)',
        'id': 4,
        'ft': ''
    }],
    json5 : [{
        'val': [],
        'fn': 'id',
        'fp': {},
        'cn': '序号',
        'id': 1,
        'ft': ''
    }, {
        'val': [],
        'fn': 'createTime',
        'fp': {},
        'cn': '数据生产时间',
        'id': 2,
        'ft': ''
    }, {
        'val': [],
        'fn': 'd6Dwqpd',
        'fp': {},
        'cn': '定位器坡度(1：n)',
        'id': 3,
        'ft': ''
    }, {
        'val': [],
        'fn': 'd6Gc',
        'fp': {},
        'cn': '高差(mm)',
        'id': 4,
        'ft': ''
    }],
    json6 : [{
        'val': [],
        'fn': 'id',
        'fp': {},
        'cn': '序号',
        'id': 1,
        'ft': ''
    }, {
        'val': [],
        'fn': 'createTime',
        'fp': {},
        'cn': '数据生产时间',
        'id': 2,
        'ft': ''
    }, {
        'val': [],
        'fn': 'd7Gd1',
        'fp': {},
        'cn': '高度1(mm)',
        'id': 3,
        'ft': ''
    }, {
        'val': [],
        'fn': 'd7Gd2',
        'fp': {},
        'cn': '高度2(mm)',
        'id': 4,
        'ft': ''
    },{
        'val': [],
        'fn': 'd7Gc',
        'fp': {},
        'cn': '高差(mm)',
        'id': 5,
        'ft': ''
    }],
    json7 : [{
        'val': [],
        'fn': 'id',
        'fp': {},
        'cn': '序号',
        'id': 1,
        'ft': ''
    }, {
        'val': [],
        'fn': 'createTime',
        'fp': {},
        'cn': '数据生产时间',
        'id': 2,
        'ft': ''
    }, {
        'val': [],
        'fn': 'd8Gd1',
        'fp': {},
        'cn': '高度1(mm)',
        'id': 3,
        'ft': ''
    }, {
        'val': [],
        'fn': 'd8Xj',
        'fp': {},
        'cn': '线距(mm)',
        'id': 4,
        'ft': ''
    },{
        'val': [],
        'fn': 'd8Gc',
        'fp': {},
        'cn': '高差(mm)',
        'id': 5,
        'ft': ''
    }],
    json8 : [{
        'val': [],
        'fn': 'id',
        'fp': {},
        'cn': '序号',
        'id': 1,
        'ft': ''
    }, {
        'val': [],
        'fn': 'createTime',
        'fp': {},
        'cn': '数据生产时间',
        'id': 2,
        'ft': ''
    }, {
        'val': [],
        'fn': 'd9Spj',
        'fp': {},
        'cn': '水平距(mm)',
        'id': 3,
        'ft': ''
    },{
        'val': [],
        'fn': 'd9Czj',
        'fp': {},
        'cn': '垂直距(mm)',
        'id': 4,
        'ft': ''
    }],
    json9 : [{
        'val': [],
        'fn': 'id',
        'fp': {},
        'cn': '序号',
        'id': 1,
        'ft': ''
    }, {
        'val': [],
        'fn': 'createTime',
        'fp': {},
        'cn': '数据生产时间',
        'id': 2,
        'ft': ''
    }, {
        'val': [],
        'fn': 'dcZzczd',
        'fp': {},
        'cn': '支柱垂直度(0.1‰)',
        'id': 3,
        'ft': ''
    }],
    json10 : [{
        'val': [],
        'fn': 'id',
        'fp': {},
        'cn': '序号',
        'id': 1,
        'ft': ''
    }, {
        'val': [],
        'fn': 'createTime',
        'fp': {},
        'cn': '数据生产时间',
        'id': 2,
        'ft': ''
    }, {
        'val': [],
        'fn': 'deZzkj',
        'fp': {},
        'cn': '支柱跨距(mm)',
        'id': 3,
        'ft': ''
    },{
        'val': [],
        'fn': 'createTime',
        'fp': {},
        'cn': '数据生产时间',
        'id': 4,
        'ft': ''
    }]
}
export default formJson
